import { StyleSheet, ScrollView, View, TouchableOpacity } from 'react-native';
import { ThemedText } from '@/components/themed-text';
import { Colors } from '@/constants/Colors';
import { useColorScheme } from '@/hooks/use-color-scheme';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { Stack } from 'expo-router';

export default function VisitSummaryScreen() {
    const colorScheme = useColorScheme() ?? 'light';
    const theme = Colors[colorScheme];

    return (
        <>
            <Stack.Screen options={{ headerShown: false }} />
            <ScrollView style={[styles.container, { backgroundColor: theme.background }]}>
                <View style={styles.header}>
                    <TouchableOpacity>
                        <IconSymbol name="chevron.left" size={24} color={theme.text} />
                    </TouchableOpacity>
                    <ThemedText type="title" style={styles.title}>Today's Visit Summary</ThemedText>
                    <View style={{ width: 24 }} />
                </View>

                <View style={styles.content}>
                    <View style={styles.audioCard}>
                        <View style={[styles.micIcon, { backgroundColor: theme.primary + '20' }]}>
                            <IconSymbol name="mic.fill" size={20} color={theme.primary} />
                        </View>
                        <View>
                            <ThemedText style={{ fontSize: 12, color: theme.icon }}>Audio Recorded: 12:34 PM</ThemedText>
                            <ThemedText style={{ fontSize: 12, color: theme.icon }}>Duration: 15m 22s</ThemedText>
                        </View>
                    </View>
                    <ThemedText style={{ color: theme.primary, fontSize: 12, textAlign: 'center', marginBottom: 20 }}>Generated by Svasthya AI</ThemedText>

                    {/* Diagnosis */}
                    <View style={[styles.card, { backgroundColor: theme.cardBackground }]}>
                        <View style={styles.cardHeader}>
                            <IconSymbol name="stethoscope" size={20} color={theme.primary} />
                            <ThemedText type="defaultSemiBold" style={{ marginLeft: 8 }}>Diagnosis</ThemedText>
                        </View>
                        <ThemedText style={{ color: theme.icon, marginTop: 8, lineHeight: 20 }}>
                            Patient exhibits symptoms consistent with seasonal allergies, including sneezing, itchy eyes, and nasal congestion. No other significant health concerns were noted during the examination.
                        </ThemedText>
                    </View>

                    {/* Prescribed Medicines */}
                    <View style={[styles.card, { backgroundColor: theme.cardBackground }]}>
                        <View style={styles.cardHeader}>
                            <IconSymbol name="pills.fill" size={20} color={theme.primary} />
                            <ThemedText type="defaultSemiBold" style={{ marginLeft: 8 }}>Prescribed Medicines</ThemedText>
                        </View>
                        <ThemedText style={{ color: theme.icon, marginTop: 8, lineHeight: 20 }}>
                            The patient has been prescribed an antihistamine to alleviate allergy symptoms.
                        </ThemedText>

                        <View style={[styles.dosageCard, { backgroundColor: theme.secondary }]}>
                            <ThemedText type="defaultSemiBold" style={{ fontSize: 12 }}>Dosage</ThemedText>
                            <ThemedText style={{ color: theme.icon, fontSize: 12, marginTop: 4 }}>
                                One tablet daily for two weeks. Please follow up if symptoms persist or worsen.
                            </ThemedText>
                        </View>
                    </View>

                    {/* Follow-up Advice */}
                    <View style={[styles.card, { backgroundColor: theme.cardBackground }]}>
                        <View style={styles.cardHeader}>
                            <IconSymbol name="calendar" size={20} color={theme.primary} />
                            <ThemedText type="defaultSemiBold" style={{ marginLeft: 8 }}>Follow-up Advice</ThemedText>
                        </View>
                        <ThemedText style={{ color: theme.icon, marginTop: 8, lineHeight: 20 }}>
                            Continue monitoring symptoms and adhere to the prescribed medication regimen. A follow-up appointment is recommended in two weeks to assess progress and adjust treatment if necessary.
                        </ThemedText>
                    </View>

                </View>
            </ScrollView>
        </>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 20,
    },
    title: {
        fontSize: 18,
    },
    content: {
        padding: 20,
        gap: 16,
    },
    audioCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
    },
    micIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    card: {
        borderRadius: 20,
        padding: 20,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    dosageCard: {
        marginTop: 12,
        padding: 12,
        borderRadius: 12,
    },
});
